# Generated by Django 5.0 on 2024-04-21 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0003_cliente_bairro_cliente_cep_cliente_cidade_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renavam', models.IntegerField(max_length=11)),
                ('placa', models.CharField(max_length=7)),
                ('processo', models.IntegerField(max_length=13)),
                ('name', models.CharField(max_length=40)),
                ('cpf_cnpj', models.CharField(max_length=14)),
                ('telefone', models.CharField(max_length=11)),
                ('cep', models.CharField(default='', max_length=50)),
                ('bairro', models.CharField(default='', max_length=30)),
                ('cidade', models.CharField(default='', max_length=15)),
                ('numero', models.CharField(default='', max_length=6)),
                ('servico', models.CharField(default='', max_length=30)),
                ('valor', models.CharField(default='', max_length=12)),
                ('chassi', models.CharField(default='', max_length=30)),
                ('cor', models.CharField(default='', max_length=14)),
                ('combustivel', models.CharField(default='', max_length=15)),
                ('data', models.DateField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]
