# Generated by Django 5.0 on 2024-04-21 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='processo',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='renavam',
            field=models.IntegerField(),
        ),
    ]
