# Generated by Django 5.0 on 2024-04-21 02:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0003_rename_cliente_ordemservico_cliente_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='cpf_cnpj',
        ),
    ]
