# Generated by Django 5.0 on 2024-04-26 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0005_ordemservico_cpf_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='telefone',
        ),
    ]
