# Generated by Django 5.0 on 2024-05-14 17:26

from django.db import migrations, models
import datetime
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0006_remove_ordemservico_bairro_remove_ordemservico_cep_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('custo', models.CharField(max_length=10)),
                ('valor_liquido', models.CharField(max_length=10)),
                ('valor_total', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='ano_veiculo',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_entrega',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='desconto',
            field=models.CharField(max_length=10, default=''),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='modelo',
            field=models.CharField(max_length=25, default=''),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='pendencias',
            field=models.CharField(max_length=25, default=''),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='valor_f',
            field=models.CharField(max_length=10, default=''),
        ),
    ]
