# Generated by Django 5.0 on 2024-05-14 17:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0007_servico_ordemservico_ano_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='ano_veiculo',
            field=models.CharField(default='', max_length=5),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_entrega',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='desconto',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_f',
            field=models.CharField(default='', max_length=10),
        ),
    ]
