# Generated by Django 5.0 on 2024-05-14 17:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0008_alter_ordemservico_ano_veiculo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='ano_veiculo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
