# Generated by Django 5.0 on 2024-05-15 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0010_alter_ordemservico_ano_veiculo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='ano_veiculo',
            field=models.CharField(default='', max_length=5),
        ),
    ]
