# Generated by Django 5.0 on 2024-05-15 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0011_alter_ordemservico_ano_veiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='ano_veiculo',
            new_name='ano_modelo',
        ),
    ]
