# Generated by Django 5.0 on 2024-05-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0012_rename_ano_veiculo_ordemservico_ano_modelo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='pendencias',
            field=models.CharField(default='', max_length=40),
        ),
    ]
