# Generated by Django 5.0 on 2024-05-19 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0015_remove_ordemservico_processo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordemservico',
            name='servico',
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='valor',
        ),
    ]
