# Generated by Django 5.0 on 2024-05-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0017_remove_ordemservico_cpf_cnpj'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='valor_veiculo',
            field=models.CharField(default='', max_length=6),
        ),
    ]
