# Generated by Django 5.0 on 2024-06-05 14:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0018_ordemservico_valor_veiculo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_doc', models.CharField(default='', max_length=30)),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('ordem_servico_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.ordemservico')),
            ],
        ),
    ]
