# Generated by Django 5.0 on 2024-06-05 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0019_documentos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='data',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
