# Generated by Django 5.0 on 2024-06-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0020_alter_ordemservico_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='data',
            new_name='data_servico',
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='data_aq',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='data_entrega',
            field=models.DateField(blank=True, null=True),
        ),
    ]
