# Generated by Django 5.0 on 2024-07-27 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0021_rename_data_ordemservico_data_servico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='observacoes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
