# Generated by Django 5.0 on 2024-07-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0022_ordemservico_observacoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='status',
            field=models.CharField(default='', max_length=20),
        ),
    ]
