# Generated by Django 5.0 on 2024-07-31 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0023_ordemservico_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servico',
            name='taxa_detran',
            field=models.CharField(default='', max_length=10),
        ),
    ]
