# Generated by Django 5.0 on 2024-08-13 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0024_servico_notas_servico_taxa_detran'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='concessionaria',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='ordemservico',
            name='cpf_comprador',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='pendencias',
            field=models.CharField(default='', max_length=30),
        ),
    ]
