# Generated by Django 5.0 on 2024-08-17 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0025_ordemservico_concessionaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='tipo_veiculo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
