# Generated by Django 5.0 on 2024-09-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0026_ordemservico_tipo_veiculo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordemservico',
            old_name='cpf_comprador',
            new_name='cpf_vendedor',
        ),
        migrations.AlterField(
            model_name='servico',
            name='custo',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='taxa_detran',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_liquido',
            field=models.CharField(default='0', max_length=10),
        ),
        migrations.AlterField(
            model_name='servico',
            name='valor_total',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
