# Generated by Django 5.0 on 2024-09-12 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0027_rename_cpf_comprador_ordemservico_cpf_vendedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='placa',
            field=models.CharField(max_length=9),
        ),
    ]
