# Generated by Django 5.0 on 2024-09-12 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0028_alter_ordemservico_placa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='placa',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_veiculo',
            field=models.CharField(default='', max_length=10),
        ),
    ]
