# Generated by Django 5.0 on 2024-09-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0029_alter_ordemservico_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='ano_modelo',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='renavam',
            field=models.CharField(max_length=50),
        ),
    ]
