# Generated by Django 5.0 on 2024-10-07 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0030_alter_ordemservico_ano_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
