# Generated by Django 5.0 on 2024-10-09 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0031_servico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='placa',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_veiculo',
            field=models.CharField(default='', max_length=15),
        ),
    ]
