# Generated by Django 5.0 on 2024-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0032_alter_ordemservico_placa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='cor',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='desconto',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_f',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='servico_os',
            name='valor_servico',
            field=models.CharField(default='', max_length=15),
        ),
    ]
