# Generated by Django 5.0 on 2024-11-18 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0033_alter_ordemservico_cor_alter_ordemservico_desconto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='concessionaria',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='desconto',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='modelo',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='pendencias',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='renavam',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='valor_f',
            field=models.CharField(default='', max_length=30),
        ),
    ]
