# Generated by Django 5.0 on 2024-12-24 19:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0034_alter_ordemservico_concessionaria_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eventos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(default='', max_length=30)),
                ('status_atual', models.CharField(default='', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('arquivo', models.FileField(upload_to='documents/')),
                ('os_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.ordemservico')),
            ],
        ),
    ]
