# Generated by Django 5.0 on 2024-12-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0035_eventos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventos',
            old_name='os_id',
            new_name='os',
        ),
        migrations.AlterField(
            model_name='eventos',
            name='arquivo',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
