# Generated by Django 5.0 on 2025-01-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0036_rename_os_id_eventos_os_alter_eventos_arquivo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='honorarios',
            field=models.CharField(default='0', max_length=10),
        ),
    ]
