# Generated by Django 5.0 on 2025-01-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0037_servico_honorarios'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='nome_vendedor',
            field=models.CharField(default='', max_length=25),
        ),
    ]
