# Generated by Django 5.0 on 2025-01-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0038_ordemservico_nome_vendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='descricao',
            field=models.CharField(max_length=90),
        ),
        migrations.AlterField(
            model_name='servico',
            name='nome',
            field=models.CharField(default='', max_length=85),
        ),
    ]
