# Generated by Django 5.0 on 2025-01-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0039_alter_servico_descricao_alter_servico_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='nome_vendedor',
            field=models.CharField(default='', max_length=50),
        ),
    ]
