# Generated by Django 5.0 on 2025-05-07 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OS', '0040_alter_ordemservico_nome_vendedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='custo_f',
            field=models.CharField(default='', max_length=30),
        ),
    ]
