# Generated by Django 5.0 on 2024-11-20 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=100)),
                ('meses', models.TextField()),
                ('quantidade', models.TextField()),
                ('data_atualizacao', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
