# Generated by Django 5.0 on 2025-01-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('cnpj', models.CharField(default='', max_length=25)),
                ('logo', models.ImageField(upload_to='clients_image/')),
                ('logo_base64', models.TextField()),
                ('telefone', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
                ('bairro', models.CharField(default='', max_length=50)),
                ('cidade', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
