# Generated by Django 5.0 on 2025-01-14 18:42

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('OS', '0036_rename_os_id_eventos_os_alter_eventos_arquivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='', max_length=50)),
                ('forma_pagamento', models.CharField(default='', max_length=50)),
                ('data_vencimento', models.DateField(blank=True, null=True)),
                ('solicitante', models.CharField(default='', max_length=100)),
                ('tomador', models.CharField(default='', max_length=100)),
                ('n_parcelas', models.IntegerField(default=1)),
                ('valor_final', models.CharField(max_length=50)),
                ('custo_final', models.CharField(max_length=50)),
                ('arrecadacao_final', models.CharField(max_length=50)),
                ('lucro_total', models.CharField(default='', max_length=50)),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='OS.ordemservico')),
            ],
        ),
        migrations.CreateModel(
            name='EventoFatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_anterior', models.CharField(default='', max_length=30)),
                ('status_atual', models.CharField(default='', max_length=30)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('data', models.DateField(default=datetime.date.today)),
                ('horario', models.TimeField(auto_now_add=True)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.fatura')),
            ],
        ),
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numeracao', models.IntegerField(default=0)),
                ('valor_parcela', models.CharField(default='', max_length=20)),
                ('status', models.CharField(default='', max_length=20)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.fatura')),
            ],
        ),
    ]
