# Generated by Django 5.0 on 2025-01-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='arrecadacao_final',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='custo_final',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='forma_pagamento',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='lucro_total',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='n_parcelas',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='tomador',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
