# Generated by Django 5.0 on 2025-05-07 00:43

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0002_alter_fatura_arrecadacao_final_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='custo_final',
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.CharField(default='', max_length=20)),
                ('forma_pagamento', models.CharField(default='', max_length=30)),
                ('data_pagamento', models.DateField(default=datetime.date.today)),
                ('fatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faturamento.fatura')),
            ],
        ),
        migrations.DeleteModel(
            name='Parcela',
        ),
    ]
