# Generated by Django 5.0 on 2025-05-08 19:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0003_remove_fatura_custo_final_pagamento_delete_parcela'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fatura',
            name='arrecadacao_final',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='forma_pagamento',
        ),
        migrations.RemoveField(
            model_name='fatura',
            name='lucro_total',
        ),
        migrations.AddField(
            model_name='fatura',
            name='data_criacao',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(default=datetime.date(2025, 5, 11)),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='solicitante',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='fatura',
            name='valor_final',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
