# Generated by Django 5.0 on 2025-05-12 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faturamento', '0004_remove_fatura_arrecadacao_final_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fatura',
            name='data_vencimento',
            field=models.DateField(default=datetime.date(2025, 5, 15)),
        ),
    ]
