# Generated by Django 5.0 on 2024-10-14 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_alter_cliente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cidade',
            field=models.CharField(default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cnpj',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='numero',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefone',
            field=models.CharField(max_length=25),
        ),
    ]
