# Generated by Django 5.0 on 2024-11-10 15:04

from django.db import migrations, models
from datetime import datetime

def add_default_date(apps, schema_editor):
    Cliente = apps.get_model('clientes', 'Cliente')
    # Define a data padrão para registros existentes
    Cliente.objects.filter(data_criacao__isnull=True).update(data_criacao=datetime(2024, 1, 1))

class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_alter_cliente_cidade_alter_cliente_cpf_cnpj_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.RunPython(add_default_date),
    ]
