# Generated by Django 5.0 on 2025-02-10 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_cliente_data_criacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='rua',
            field=models.CharField(default='', max_length=100),
        ),
    ]
